/* ------------------------------------------------------------------ *
 * Beast Battle Arena — fighter definitions.
 * speed is in arena units per millisecond; damage is per landed hit.
 * ------------------------------------------------------------------ */

export const MAX_HP = 100;
export const MAX_METER = 100;

export const ROSTER = [
  {
    id: "lion",
    name: "Lion",
    title: "The Pride King",
    style: "Heavy Hitter",
    blurb: "Slow across the sand, but every paw strike lands like a falling tree.",
    stats: { power: 9, speed: 5, reach: 8 },
    speed: 0.27,
    attack: 12,
    attackTime: 420,
    attackHit: [120, 250],
    range: 210,
    comboMax: 1,
    accent: "#f0a83c",
    coat: "#c98c3c",
    special: {
      name: "Thunder Roar",
      type: "roar",
      damage: 26,
      desc: "A roar so deep it blasts a shockwave across the whole arena.",
    },
    voice: "lionRoar",
  },
  {
    id: "tiger",
    name: "Tiger",
    title: "Striped Ambusher",
    style: "Combo Striker",
    blurb: "Fastest claws in the arena — chains three strikes before you can guard.",
    stats: { power: 7, speed: 8, reach: 6 },
    speed: 0.4,
    attack: 7,
    attackTime: 260,
    attackHit: [70, 165],
    range: 180,
    comboMax: 3,
    accent: "#ff9b3d",
    coat: "#e07b23",
    special: {
      name: "Claw Frenzy",
      type: "frenzy",
      damage: 8,
      hits: 3,
      desc: "Blurs forward and rakes the opponent with a three-hit claw flurry.",
    },
    voice: "tigerGrowl",
  },
  {
    id: "gorilla",
    name: "Gorilla",
    title: "Silverback Titan",
    style: "Powerhouse",
    blurb: "The strongest fighter alive. Slow, immovable, and utterly overwhelming.",
    stats: { power: 10, speed: 3, reach: 7 },
    speed: 0.22,
    attack: 14,
    attackTime: 480,
    attackHit: [150, 290],
    range: 192,
    comboMax: 1,
    accent: "#9fb2c8",
    coat: "#4a4a55",
    special: {
      name: "Ground Smash",
      type: "smash",
      damage: 28,
      desc: "Leaps up and hammers the ground, shaking the whole arena.",
    },
    voice: "gorillaPound",
  },
  {
    id: "wolf",
    name: "Wolf",
    title: "Grey Pack Leader",
    style: "Agile Duelist",
    blurb: "Circles, darts in for a fast two-hit combo, and slips straight back out.",
    stats: { power: 6, speed: 9, reach: 6 },
    speed: 0.42,
    attack: 6,
    attackTime: 240,
    attackHit: [60, 150],
    range: 180,
    comboMax: 2,
    accent: "#a8c4dd",
    coat: "#77808e",
    special: {
      name: "Fang Rush",
      type: "rush",
      damage: 20,
      desc: "Explodes forward in a low rush that closes any gap instantly.",
    },
    voice: "wolfHowl",
  },
  {
    id: "eagle",
    name: "Eagle",
    title: "Storm Talon",
    style: "Aerial Skirmisher",
    blurb: "Lightest hits in the arena, but no one strikes faster or fights from the air.",
    stats: { power: 4, speed: 9, reach: 7 },
    speed: 0.46,
    attack: 5,
    attackTime: 215,
    attackHit: [55, 140],
    range: 184,
    comboMax: 2,
    accent: "#ffd15c",
    coat: "#7a5330",
    special: {
      name: "Sky Dive",
      type: "dive",
      damage: 18,
      desc: "Climbs out of reach, then drops talons-first from across the arena.",
    },
    voice: "eagleScreech",
  },
  {
    id: "dragon",
    name: "Dragon",
    title: "Ashfall Wyrm",
    style: "Zone Controller",
    fantasy: true,
    blurb: "A creature of myth among the beasts — slow on the ground, deadly at any range.",
    stats: { power: 8, speed: 4, reach: 10 },
    speed: 0.24,
    attack: 9,
    attackTime: 400,
    attackHit: [110, 240],
    range: 200,
    comboMax: 1,
    accent: "#ff8a3d",
    coat: "#7d51d8",
    special: {
      name: "Fire Breath",
      type: "fire",
      damage: 24,
      desc: "Breathes a stream of fire that rolls across the arena and burns on contact.",
    },
    voice: "dragonRoar",
  },
  {
    id: "cheetah",
    name: "Cheetah",
    title: "Dust Runner",
    style: "Speed Skirmisher",
    blurb: "The fastest legs in the arena. Hits light, but is gone before you swing back.",
    stats: { power: 5, speed: 10, reach: 5 },
    speed: 0.55,
    attack: 5,
    attackTime: 240,
    attackHit: [62, 155],
    range: 176,
    comboMax: 3,
    accent: "#ffe08a",
    coat: "#d9a94a",
    special: {
      name: "Blur Sprint",
      type: "blur",
      damage: 13,
      hits: 2,
      desc: "Sprints clean through the opponent, striking on the way in and the way past.",
    },
    voice: "cheetahChirp",
  },
  {
    id: "elephant",
    name: "Elephant",
    title: "Grey Mountain",
    style: "Siege Bruiser",
    blurb: "Slowest fighter alive and the longest reach — one connected blow changes a round.",
    stats: { power: 9, speed: 2, reach: 9 },
    speed: 0.18,
    attack: 13,
    attackTime: 520,
    attackHit: [165, 320],
    range: 224,
    comboMax: 1,
    accent: "#d7ddec",
    coat: "#8d93a6",
    special: {
      name: "Thunder Stomp",
      type: "stomp",
      damage: 25,
      desc: "Slams a foreleg down and sends a ground wave rolling at the opponent.",
    },
    voice: "elephantTrumpet",
  },
  {
    id: "crocodile",
    name: "Crocodile",
    title: "River Tyrant",
    style: "Counter Puncher",
    blurb: "Low, patient and armoured. Waits out your combo, then answers with the jaws.",
    stats: { power: 8, speed: 4, reach: 7 },
    speed: 0.26,
    attack: 10,
    attackTime: 400,
    attackHit: [115, 245],
    range: 186,
    comboMax: 1,
    accent: "#a8e06a",
    coat: "#4f8a4a",
    special: {
      name: "Crushing Bite",
      type: "bite",
      damage: 27,
      desc: "Lunges in and clamps down — the hardest single hit in the game, if it reaches.",
    },
    voice: "crocHiss",
  },
  {
    id: "rhino",
    name: "Rhino",
    title: "Iron Horn",
    style: "Armoured Charger",
    blurb: "Built like a wall on the move. Shrugs off damage while the horn is down.",
    stats: { power: 9, speed: 5, reach: 7 },
    speed: 0.3,
    attack: 11,
    attackTime: 440,
    attackHit: [130, 265],
    range: 190,
    comboMax: 1,
    accent: "#dbe4ee",
    coat: "#7d8794",
    special: {
      name: "Horn Rush",
      type: "gore",
      damage: 23,
      desc: "Lowers the horn and charges — takes half damage for as long as the rush lasts.",
    },
    voice: "rhinoSnort",
  },
];

export const byId = (id) => ROSTER.find((c) => c.id === id) || ROSTER[0];

export const ARENAS = [
  { id: "jungle", name: "Jungle Ruins" },
  { id: "canyon", name: "Rocky Canyon" },
  { id: "savannah", name: "Golden Savannah" },
  { id: "night", name: "Night Arena" },
];
